"""Problem table

Revision ID: 20e438d5d947
Revises: 6df56befc934
Create Date: 2025-11-28 20:48:03.967663

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20e438d5d947'
down_revision: Union[str, Sequence[str], None] = '6df56befc934'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('problem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('history_id', sa.Integer(), nullable=False),
    sa.Column('monitor_id', sa.Integer(), nullable=False),
    sa.Column('duckduckgo_search_data', sa.JSON(), nullable=True),
    sa.Column('ai_analysis', sa.Text(), nullable=True),
    sa.Column('ai_recommendations', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['history_id'], ['monitor_history.id'], ),
    sa.ForeignKeyConstraint(['monitor_id'], ['monitors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('monitor_history', sa.Column('latency', sa.Float(), nullable=True))
    op.drop_column('monitor_history', 'response_time')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('monitor_history', sa.Column('response_time', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('monitor_history', 'latency')
    op.drop_table('problem')
    # ### end Alembic commands ###
