"""Monitor History Timezone

Revision ID: cd1a7800c9c3
Revises: 20e438d5d947
Create Date: 2025-12-01 09:13:57.894264

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cd1a7800c9c3'
down_revision: Union[str, Sequence[str], None] = '20e438d5d947'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('monitor_history', sa.Column('checked_at', sa.DateTime(timezone=True), nullable=False))
    op.drop_column('monitor_history', 'checked_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('monitor_history', sa.Column('checked_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('monitor_history', 'created_at')
    # ### end Alembic commands ###
